load("@bazel_skylib//rules:build_test.bzl", "build_test")
load(":action_test.bzl", "action_fixture", "hardening_emitted_test")
load(":hardening_test.bzl", "hardening_test")
load(":platform_transition.bzl", "with_platform")
load(":semver_test.bzl", "semver_test_suite")

package(default_visibility = ["//visibility:private"])

semver_test_suite(name = "semver")

action_fixture(name = "action_fixture")

hardening_emitted_test(
    name = "hardening_emitted_test",
    target_under_test = ":action_fixture",
)

hardening_test(name = "hardening_test")

with_platform(
    name = "fixture_darwin_aarch64",
    platform = "//bun/tests/platforms:darwin_aarch64",
    target = [":action_fixture"],
)

build_test(
    name = "cross_darwin_aarch64_test",
    targets = [":fixture_darwin_aarch64"],
)

with_platform(
    name = "fixture_linux_aarch64",
    platform = "//bun/tests/platforms:linux_aarch64",
    target = [":action_fixture"],
)

build_test(
    name = "cross_linux_aarch64_test",
    targets = [":fixture_linux_aarch64"],
)

with_platform(
    name = "fixture_windows_x64",
    platform = "//bun/tests/platforms:windows_x64",
    target = [":action_fixture"],
)

build_test(
    name = "cross_windows_x64_test",
    targets = [":fixture_windows_x64"],
)
