load("//bun:toolchain.bzl", "bun_toolchain")
load(":semver_test.bzl", "semver_test_suite")
load(
    ":toolchain_test.bzl",
    "bun_bin_genrule_test",
    "bun_bin_value_test",
    "exec_cfg_test_suite",
    "resolved_bun",
    "toolchain_rejection_test_suite",
    "toolchain_selection_test_suite",
)
load(":versions_test.bzl", "versions_test_suite")

package(default_visibility = ["//visibility:private"])

semver_test_suite(name = "semver")

versions_test_suite(name = "versions")

toolchain_selection_test_suite(name = "selection")

toolchain_rejection_test_suite(name = "rejection")

exec_cfg_test_suite(name = "exec_cfg")

bun_toolchain(
    name = "bun_bin_toolchain",
    bun = "@bun_linux-x64//:bun",
    version = "0.0.0",
)

bun_bin_value_test(
    name = "bun_bin_value_test",
    target_under_test = ":bun_bin_toolchain",
)

genrule(
    name = "bun_bin_genrule",
    outs = ["bun_bin_genrule.txt"],
    cmd = "$(BUN_BIN) --version > $@",
    cmd_bat = "$(BUN_BIN) --version > $@",
    tags = ["manual"],
    toolchains = ["//bun/toolchain:execution_type"],
)

resolved_bun(name = "bun_bin_resolved")

bun_bin_genrule_test(
    name = "bun_bin_genrule_test",
    resolved = ":bun_bin_resolved",
    target_under_test = ":bun_bin_genrule",
)
