load("@bazel_skylib//rules:diff_test.bzl", "diff_test")
load("@bazel_skylib//rules:write_file.bzl", "write_file")
load(":verify.bzl", "verify_toolchain")
load(":verify_test.bzl", "toolchain_param_test")

verify_toolchain(name = "verify")

toolchain_param_test(
    name = "toolchain_param_test",
    target_under_test = ":verify",
)

write_file(
    name = "expected_version",
    out = "expected_version.txt",
    content = [
        "1.4.2",
        "",
    ],
    newline = "unix",
)

diff_test(
    name = "version_test",
    failure_message = "The Bun from the registered toolchain reported a version other than the expected one.",
    file1 = ":verify",
    file2 = ":expected_version",
)
