module(name = "rules_bun_e2e_smoke")

bazel_dep(name = "rules_bun", version = "0.0.0")
local_path_override(
    module_name = "rules_bun",
    path = "../..",
)

bun = use_extension("@rules_bun//bun:extensions.bzl", "bun")
bun.toolchain(bun_version = "1.4.2")
use_repo(bun, "bun_toolchains")

register_toolchains("@bun_toolchains//:all")
