load("@bazel_lib//:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//bun:__subpackages__"])

bzl_library(
    name = "action",
    srcs = ["action.bzl"],
    deps = [":hardening"],
)

bzl_library(
    name = "toolchains_repo",
    srcs = ["toolchains_repo.bzl"],
    deps = [":platforms"],
)

bzl_library(
    name = "hardening",
    srcs = ["hardening.bzl"],
)

bzl_library(
    name = "paths",
    srcs = ["paths.bzl"],
)

bzl_library(
    name = "platforms",
    srcs = ["platforms.bzl"],
)

bzl_library(
    name = "providers",
    srcs = ["providers.bzl"],
)

bzl_library(
    name = "semver",
    srcs = ["semver.bzl"],
)

bzl_library(
    name = "versions",
    srcs = ["versions.bzl"],
)
