load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//bun:__subpackages__"])

[
    bzl_library(
        name = name,
        srcs = [name + ".bzl"],
        visibility = ["//visibility:public"],
    )
    for name in [
        "platforms",
        "providers",
        "semver",
        "paths",
        "versions",
    ]
]

bzl_library(
    name = "hardening",
    srcs = ["hardening.bzl"],
)

bzl_library(
    name = "action",
    srcs = ["action.bzl"],
    deps = [":hardening"],
)

bzl_library(
    name = "toolchains_repo",
    srcs = ["toolchains_repo.bzl"],
    visibility = ["//visibility:public"],
    deps = [":platforms"],
)
