name: Release
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  id-token: write
  attestations: write
  contents: write
jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7.7.0
    with:
      release_files: rules_bun-*.tar.gz
      prerelease: false
      draft: true
      tag_name: ${{ github.ref_name }}
  publish:
    needs: release
    uses: ./.github/workflows/publish.yaml
    with:
      tag_name: ${{ github.ref_name }}
    secrets: inherit
  finalize:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v3.0.3
        with:
          tag_name: ${{ github.ref_name }}
